// Tipos derivados del contrato: `npm run gen:api` regenera `openapi.d.ts` desde docs/architecture/openapi.yaml.
import type { components } from './openapi'

type S = components['schemas']

export type TokenResponse = S['TokenResponse']
export type LoadPlanRequest = S['LoadPlanRequest']
export type LoadPlanResponse = S['LoadPlanResponse']
export type LoadPlanItem = S['LoadPlanItem']
export type DemandRequest = S['DemandRequest']
export type DemandResponse = S['DemandResponse']
export type MetricsResponse = S['MetricsResponse']
export type MetricPoint = S['MetricPoint']
export type PeorProducto = S['PeorProducto']
export type RetrainRequest = S['RetrainRequest']
export type RetrainResponse = S['RetrainResponse']
export type JobStatus = S['JobStatus']
export type ModeloResumen = S['ModeloResumen']
export type MlConfig = S['MlConfig']
export type AlertList = S['AlertList']
export type RouteItem = S['RouteItem']
export type SugerenciaCompra = S['SugerenciaCompra']
export type SugerenciasResponse = S['SugerenciasResponse']
export type PedidoCreate = S['PedidoCreate']
export type PedidoOut = S['PedidoOut']
export type PedidoPage = S['PedidoPage']
export type StockItem = S['StockItem']
export type ProductoOut = S['ProductoOut']
export type ProductoPage = S['ProductoPage']
export type ProductoCreate = S['ProductoCreate']
export type ProductoUpdate = S['ProductoUpdate']
export type AjusteRequest = S['AjusteRequest']
export type AjusteResponse = S['AjusteResponse']
export type CategoriaItem = S['CategoriaItem']
export type ProveedorItem = S['ProveedorItem']
export type TipoAjuste = S['TipoAjuste']
export type StockPage = S['StockPage']
export type KardexEntry = S['KardexEntry']
export type KardexPage = S['KardexPage']

export type AlertItem = S['AlertItem']
export type UsuarioOut = S['UsuarioOut']
export type UsuarioPage = S['UsuarioPage']
export type UsuarioCreate = S['UsuarioCreate']
export type UsuarioUpdate = S['UsuarioUpdate']
export type RolItem = S['RolItem']
export type EtlResult = S['EtlResult']
export type EtlValidationError = S['EtlValidationError']
export type ErrorFila = S['ErrorFila']
export type LoteItem = S['LoteItem']
export type LotePage = S['LotePage']
export type LiquidacionRequest = S['LiquidacionRequest']
export type LineaLiquidacion = S['LineaLiquidacion']
export type PagosLiquidacion = S['PagosLiquidacion-Input']
export type LiquidacionResponse = S['LiquidacionResponse']
export type LineaRespuesta = S['LineaRespuesta']
export type LiquidacionResumen = S['LiquidacionResumen']
export type ListadoLiquidaciones = S['ListadoLiquidaciones']
export type PrecargaResponse = S['PrecargaResponse']
export type LineaPrecarga = S['LineaPrecarga']
export type LiquidacionConfig = S['LiquidacionConfig-Output']
export type EtlConfig = S['EtlConfig']
export type EstadoLiquidacion = LiquidacionResponse['estado']
export type RotacionReporte = S['RotacionReporte']
export type RotacionRuta = S['RotacionRuta']
export type ComisionReporte = S['ComisionReporte']
export type ComisionVendedor = S['ComisionVendedor']
export type VentasProyeccionReporte = S['VentasProyeccionReporte']

export type Algoritmo = RetrainRequest['algoritmos'][number]
export type EstadoCarga = LoadPlanResponse['estado']
export type EstadoPedido = PedidoOut['estado']
export type TipoAlerta = AlertItem['tipo']
export type TipoMovimiento = KardexEntry['tipo_movimiento']

export interface ApiError {
  codigo: string
  mensaje: string
  detalle?: Record<string, unknown>
}
