/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autenticación y emisión de JWT */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/etl/upload-excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingesta de histórico de ventas desde Excel
         * @description Requiere permiso `etl:cargar`. Valida estructura, tipos y reglas de negocio. Si existen errores bloqueantes el lote se rechaza completo (modo estricto) salvo `modo=parcial`. Un archivo con checksum ya cargado devuelve 400 `LOTE_DUPLICADO`.
         */
        post: operations["upload_excel_api_v1_etl_upload_excel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions/demand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inferencia de demanda por producto/ruta/horizonte
         * @description Requiere permiso `prediccion:consultar`. Usa el modelo en estado `produccion` (400 `SIN_MODELO_PRODUCTIVO` si no existe). El intervalo es al 95 %. Con `persistir=true` guarda los puntos en `pronosticos_demanda` (idempotente).
         */
        post: operations["predecir_demanda_api_v1_predictions_demand_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/load-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Carga vigente de una ruta y fecha
         * @description Requiere `carga_ruta:generar` o `carga_ruta:aprobar`. Devuelve la carga vigente (borrador, pendiente o aprobada) o 404 `CARGA_NO_ENCONTRADA`.
         */
        get: operations["obtener_carga_vigente_api_v1_routes_load_plans_get"];
        put?: never;
        /**
         * Generación y aprobación de carga de ruta
         * @description `accion=generar` (permiso `carga_ruta:generar`) crea un plan en `borrador` con `cantidad_sugerida = min(demanda predicha, stock disponible)`; 400 `CARGA_VIGENTE_EXISTENTE` si ya hay una carga vigente para la ruta y fecha. `accion=enviar` (permiso `carga_ruta:generar`) pasa un `borrador` a `pendiente_aprobacion`. `accion=aprobar|rechazar` (permiso `carga_ruta:aprobar`) opera sobre `carga_id`: aprobar reserva stock y registra el kardex (400 `CANTIDAD_EXCEDE_STOCK` si una cantidad excede el disponible); rechazar exige `motivo_rechazo` y libera las reservas existentes.
         */
        post: operations["gestionar_carga_api_v1_routes_load_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Existencias por producto
         * @description Requiere permiso `inventario:leer`. `stock_disponible = stock_actual - stock_reservado`. Un producto sin fila de inventario se reporta con existencias en 0.
         */
        get: operations["listar_existencias_api_v1_inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/kardex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Movimientos de kardex
         * @description Requiere permiso `inventario:leer`. Orden: más reciente primero.
         */
        get: operations["listar_kardex_api_v1_inventory_kardex_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ml/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consulta de precisión y degradación
         * @description Requiere permiso `ml:metricas:leer`. Si se omite `modelo_id` se usa el modelo en producción (400 `SIN_MODELO_PRODUCTIVO` si no hay). `resumen` = periodo más reciente de `serie`; `peores_productos` = top por MAPE del último periodo en el rango. 422 si `desde` > `hasta`.
         */
        get: operations["consultar_metricas_api_v1_ml_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ml/models/retrain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disparo de reentrenamiento
         * @description Requiere permiso `ml:reentrenar` (403 `PERMISO_DENEGADO` en caso contrario, sin crear job). Encola un job asíncrono y responde con `job_id` y estado `en_cola`; el candidato solo se promueve si mejora al modelo en producción. 400 `REENTRENAMIENTO_EN_CURSO` si ya hay uno activo.
         */
        post: operations["reentrenar_api_v1_ml_models_retrain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ml/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historial de modelos
         * @description Requiere permiso `ml:metricas:leer`. Más reciente primero (máx. 20).
         */
        get: operations["listar_modelos_api_v1_ml_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ml/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado de un job asíncrono
         * @description Requiere permiso `ml:metricas:leer`. Muestra el progreso del reentrenamiento.
         */
        get: operations["estado_job_api_v1_ml_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ml/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Umbral de degradación vigente
         * @description Requiere permiso `ml:metricas:leer`. Lee `ml.mape_umbral` y periodos.
         */
        get: operations["obtener_config_api_v1_ml_config_get"];
        /**
         * Guardar umbral de degradación
         * @description Requiere permiso `ml:reentrenar`. Actualiza `parametros_sistema` (ADR-08).
         */
        put: operations["guardar_config_api_v1_ml_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bandeja de alertas
         * @description Requiere permiso `alertas:leer`. Críticas primero, luego las más recientes.
         */
        get: operations["listar_alertas_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rutas activas
         * @description Cualquier usuario autenticado. Alimenta el filtro de ruta del dashboard.
         */
        get: operations["listar_rutas_api_v1_catalog_routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness del servicio
         * @description Usado por el healthcheck de Docker; no consulta la base de datos.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AjusteCarga */
        AjusteCarga: {
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Cantidad Aprobada */
            cantidad_aprobada: number | string;
        };
        /** AlertItem */
        AlertItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            tipo: components["schemas"]["TipoAlerta"];
            severidad: components["schemas"]["Severidad"];
            /** Mensaje */
            mensaje: string;
            estado: components["schemas"]["EstadoAlerta"];
            /** Producto Id */
            producto_id?: string | null;
            /** Modelo Id */
            modelo_id?: string | null;
            /**
             * Creada En
             * Format: date-time
             */
            creada_en: string;
        };
        /** AlertList */
        AlertList: {
            /** Total */
            total: number;
            /** Alertas */
            alertas: components["schemas"]["AlertItem"][];
        };
        /**
         * Algoritmo
         * @enum {string}
         */
        Algoritmo: "sklearn" | "xgboost" | "lstm";
        /** Body_upload_excel_api_v1_etl_upload_excel_post */
        Body_upload_excel_api_v1_etl_upload_excel_post: {
            /** File */
            file: string;
            /** @default estricto */
            modo: components["schemas"]["ModoCarga"];
            /**
             * Hoja
             * @description Nombre de la hoja; por defecto la primera
             */
            hoja?: string | null;
            /**
             * Periodo
             * @description YYYY-MM. Solo formato ancho; por defecto se infiere del nombre del archivo
             */
            periodo?: string | null;
        };
        /**
         * CodigoErrorEtl
         * @enum {string}
         */
        CodigoErrorEtl: "COLUMNAS_FALTANTES" | "TIPOS_INVALIDOS" | "DATOS_INVALIDOS";
        /** Degradacion */
        Degradacion: {
            /** Umbral Mape */
            umbral_mape: number;
            /** Periodos Consecutivos Requeridos */
            periodos_consecutivos_requeridos: number;
            /** Periodos Consecutivos Actuales */
            periodos_consecutivos_actuales: number;
            /** Requiere Reentrenamiento */
            requiere_reentrenamiento: boolean;
            /** Ultimo Reentrenamiento */
            ultimo_reentrenamiento?: string | null;
            /** @description Estado final del candidato del último reentrenamiento */
            ultimo_reentrenamiento_resultado?: components["schemas"]["EstadoModelo"] | null;
        };
        /** DemandModelInfo */
        DemandModelInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Algoritmo */
            algoritmo: string;
            /** Version */
            version: string;
        };
        /** DemandPoint */
        DemandPoint: {
            /**
             * Fecha Objetivo
             * Format: date
             */
            fecha_objetivo: string;
            /** Demanda Predicha */
            demanda_predicha: number;
            /** Limite Inferior */
            limite_inferior?: number | null;
            /** Limite Superior */
            limite_superior?: number | null;
        };
        /** DemandProductForecast */
        DemandProductForecast: {
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Serie */
            serie: components["schemas"]["DemandPoint"][];
        };
        /** DemandRequest */
        DemandRequest: {
            /** Producto Ids */
            producto_ids: string[];
            /**
             * Ruta Id
             * @description Si se omite, la demanda es agregada (suma de todas las rutas)
             */
            ruta_id?: string | null;
            /**
             * Fecha Base
             * @description Por defecto hoy
             */
            fecha_base?: string | null;
            /** Horizonte Dias */
            horizonte_dias: number;
            /**
             * Incluir Intervalo
             * @default true
             */
            incluir_intervalo: boolean;
            /**
             * Persistir
             * @description Guarda los pronósticos en la BD
             * @default false
             */
            persistir: boolean;
        };
        /** DemandResponse */
        DemandResponse: {
            modelo: components["schemas"]["DemandModelInfo"];
            /**
             * Generado En
             * Format: date-time
             */
            generado_en: string;
            /** Pronosticos */
            pronosticos: components["schemas"]["DemandProductForecast"][];
        };
        /**
         * ErrorFila
         * @description Error de validación localizado por fila/columna (fila = número de fila en Excel).
         */
        ErrorFila: {
            /** Fila */
            fila: number;
            /** Columna */
            columna: string;
            /** Valor */
            valor?: string | null;
            /** Mensaje */
            mensaje: string;
            /** Hoja */
            hoja?: string | null;
        };
        /**
         * EstadoAlerta
         * @enum {string}
         */
        EstadoAlerta: "abierta" | "reconocida" | "resuelta";
        /**
         * EstadoCarga
         * @enum {string}
         */
        EstadoCarga: "borrador" | "pendiente_aprobacion" | "aprobada" | "rechazada" | "despachada";
        /**
         * EstadoJob
         * @enum {string}
         */
        EstadoJob: "en_cola" | "en_ejecucion" | "completado" | "fallido";
        /**
         * EstadoModelo
         * @enum {string}
         */
        EstadoModelo: "candidato" | "produccion" | "archivado" | "descartado";
        /** EtlResult */
        EtlResult: {
            /**
             * Lote Id
             * Format: uuid
             */
            lote_id: string;
            /**
             * Estado
             * @enum {string}
             */
            estado: "cargado" | "rechazado";
            /** Filas Totales */
            filas_totales: number;
            /** Filas Validas */
            filas_validas: number;
            /** Filas Rechazadas */
            filas_rechazadas: number;
            rango_fechas?: components["schemas"]["RangoFechas"] | null;
            /** Advertencias */
            advertencias?: string[];
        };
        /** EtlValidationError */
        EtlValidationError: {
            codigo: components["schemas"]["CodigoErrorEtl"];
            /**
             * Lote Id
             * Format: uuid
             */
            lote_id: string;
            /** Errores */
            errores: components["schemas"]["ErrorFila"][];
            /** Total Errores */
            total_errores: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobStatus */
        JobStatus: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            tipo: components["schemas"]["TipoJob"];
            estado: components["schemas"]["EstadoJob"];
            /** Parametros */
            parametros: {
                [key: string]: unknown;
            };
            /** Resultado Modelo Id */
            resultado_modelo_id?: string | null;
            /**
             * Solicitado En
             * Format: date-time
             */
            solicitado_en: string;
            /** Iniciado En */
            iniciado_en?: string | null;
            /** Finalizado En */
            finalizado_en?: string | null;
            /** Error */
            error?: string | null;
        };
        /** KardexEntry */
        KardexEntry: {
            /** Id */
            id: number;
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            tipo_movimiento: components["schemas"]["TipoMovimiento"];
            /** Cantidad */
            cantidad: string;
            /** Saldo Resultante */
            saldo_resultante: string;
            referencia_tipo?: components["schemas"]["ReferenciaTipo"] | null;
            /** Referencia Id */
            referencia_id?: string | null;
            /** Usuario Id */
            usuario_id?: string | null;
            /**
             * Fecha Movimiento
             * Format: date-time
             */
            fecha_movimiento: string;
        };
        /** KardexPage */
        KardexPage: {
            /** Items */
            items: components["schemas"]["KardexEntry"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** LoadPlanItem */
        LoadPlanItem: {
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Sku */
            sku: string;
            /** Producto Nombre */
            producto_nombre?: string | null;
            /** Cantidad Predicha */
            cantidad_predicha: string;
            /**
             * Stock Disponible
             * @description Stock disponible al generar el plan
             */
            stock_disponible: string;
            /** Cantidad Sugerida */
            cantidad_sugerida: string;
            /**
             * Cantidad Aprobada
             * @description Nula hasta que el plan se aprueba
             */
            cantidad_aprobada?: string | null;
            /** Ajustado Por Stock */
            ajustado_por_stock: boolean;
        };
        /** LoadPlanRequest */
        LoadPlanRequest: {
            /**
             * Accion
             * @enum {string}
             */
            accion: "generar" | "enviar" | "aprobar" | "rechazar";
            /**
             * Ruta Id
             * @description Obligatorio si accion=generar
             */
            ruta_id?: string | null;
            /**
             * Fecha Operacion
             * @description Obligatorio si accion=generar
             */
            fecha_operacion?: string | null;
            /**
             * Carga Id
             * @description Obligatorio si accion=enviar|aprobar|rechazar
             */
            carga_id?: string | null;
            /**
             * Ajustes
             * @description Cantidades aprobadas editadas (solo accion=aprobar)
             */
            ajustes?: components["schemas"]["AjusteCarga"][] | null;
            /**
             * Motivo Rechazo
             * @description Obligatorio si accion=rechazar
             */
            motivo_rechazo?: string | null;
            /** Observaciones */
            observaciones?: string | null;
        };
        /** LoadPlanResponse */
        LoadPlanResponse: {
            /**
             * Carga Id
             * Format: uuid
             */
            carga_id: string;
            /**
             * Ruta Id
             * Format: uuid
             */
            ruta_id: string;
            /**
             * Fecha Operacion
             * Format: date
             */
            fecha_operacion: string;
            estado: components["schemas"]["EstadoCarga"];
            /**
             * Modelo Id
             * Format: uuid
             */
            modelo_id: string;
            /** Items */
            items: components["schemas"]["LoadPlanItem"][];
            /** Alertas Generadas */
            alertas_generadas?: string[];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MetricPoint */
        MetricPoint: {
            /**
             * Periodo Desde
             * Format: date
             */
            periodo_desde: string;
            /**
             * Periodo Hasta
             * Format: date
             */
            periodo_hasta: string;
            /** Mae */
            mae: number;
            /** Rmse */
            rmse: number;
            /** Mape */
            mape?: number | null;
            /** N Muestras */
            n_muestras: number;
            /**
             * Supera Umbral
             * @default false
             */
            supera_umbral: boolean;
        };
        /** MetricsResponse */
        MetricsResponse: {
            /**
             * Modelo Id
             * Format: uuid
             */
            modelo_id: string;
            modelo: components["schemas"]["ModeloInfo"];
            resumen: components["schemas"]["ResumenMetricas"];
            /** Serie */
            serie: components["schemas"]["MetricPoint"][];
            /** Peores Productos */
            peores_productos?: components["schemas"]["PeorProducto"][];
            degradacion: components["schemas"]["Degradacion"];
        };
        /** MlConfig */
        MlConfig: {
            /** Umbral Mape */
            umbral_mape: number;
            /** Periodos Consecutivos */
            periodos_consecutivos: number;
        };
        /** ModelList */
        ModelList: {
            /** Modelos */
            modelos: components["schemas"]["ModeloResumen"][];
        };
        /** ModeloInfo */
        ModeloInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            algoritmo: components["schemas"]["Algoritmo"];
            /** Version */
            version: string;
            estado: components["schemas"]["EstadoModelo"];
        };
        /** ModeloResumen */
        ModeloResumen: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version */
            version: string;
            algoritmo: components["schemas"]["Algoritmo"];
            estado: components["schemas"]["EstadoModelo"];
            motivo_entrenamiento: components["schemas"]["MotivoEntrenamiento"];
            /**
             * Entrenado En
             * Format: date-time
             */
            entrenado_en: string;
            /** Promovido En */
            promovido_en?: string | null;
            /** Mape Holdout */
            mape_holdout?: number | null;
        };
        /**
         * ModoCarga
         * @enum {string}
         */
        ModoCarga: "estricto" | "parcial";
        /**
         * MotivoEntrenamiento
         * @enum {string}
         */
        MotivoEntrenamiento: "programado" | "manual" | "degradacion";
        /** PeorProducto */
        PeorProducto: {
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Sku */
            sku?: string | null;
            /** Nombre */
            nombre?: string | null;
            /** Mae */
            mae: number;
            /** Rmse */
            rmse: number;
            /** Mape */
            mape?: number | null;
            /**
             * Tendencia
             * @description MAPE del último periodo frente al anterior
             */
            tendencia?: ("sube" | "baja" | "estable") | null;
        };
        /** RangoFechas */
        RangoFechas: {
            /**
             * Desde
             * Format: date
             */
            desde: string;
            /**
             * Hasta
             * Format: date
             */
            hasta: string;
        };
        /**
         * ReferenciaTipo
         * @enum {string}
         */
        ReferenciaTipo: "carga_ruta" | "pedido" | "ajuste" | "etl";
        /**
         * ResumenMetricas
         * @description Valores del periodo más reciente de la serie (KPI del panel).
         */
        ResumenMetricas: {
            /** Mae */
            mae?: number | null;
            /** Rmse */
            rmse?: number | null;
            /** Mape */
            mape?: number | null;
        };
        /** RetrainRequest */
        RetrainRequest: {
            /** Algoritmos */
            algoritmos: components["schemas"]["Algoritmo"][];
            motivo: components["schemas"]["MotivoEntrenamiento"];
            /** Ventana Desde */
            ventana_desde?: string | null;
            /** Ventana Hasta */
            ventana_hasta?: string | null;
            /**
             * Promover Automaticamente
             * @description Promueve si el candidato mejora el MAPE del modelo en producción
             * @default true
             */
            promover_automaticamente: boolean;
        };
        /** RetrainResponse */
        RetrainResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Estado
             * @enum {string}
             */
            estado: "en_cola" | "en_ejecucion";
            /**
             * Solicitado En
             * Format: date-time
             */
            solicitado_en: string;
        };
        /** RouteItem */
        RouteItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /** Zona */
            zona?: string | null;
        };
        /**
         * Severidad
         * @enum {string}
         */
        Severidad: "info" | "advertencia" | "critica";
        /** StockItem */
        StockItem: {
            /**
             * Producto Id
             * Format: uuid
             */
            producto_id: string;
            /** Sku */
            sku: string;
            /** Nombre */
            nombre: string;
            /** Stock Actual */
            stock_actual: string;
            /** Stock Reservado */
            stock_reservado: string;
            /** Stock Disponible */
            stock_disponible: string;
            /** Stock Minimo */
            stock_minimo: string;
            /** Bajo Minimo */
            bajo_minimo: boolean;
        };
        /** StockPage */
        StockPage: {
            /** Items */
            items: components["schemas"]["StockItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * TipoAlerta
         * @enum {string}
         */
        TipoAlerta: "stock_bajo" | "quiebre_proyectado" | "mape_umbral" | "etl_error";
        /**
         * TipoEvaluacion
         * @enum {string}
         */
        TipoEvaluacion: "holdout" | "backtest" | "produccion";
        /**
         * TipoJob
         * @enum {string}
         */
        TipoJob: "reentrenamiento" | "evaluacion_produccion" | "pronostico_nocturno";
        /**
         * TipoMovimiento
         * @enum {string}
         */
        TipoMovimiento: "entrada" | "salida" | "ajuste" | "reserva" | "liberacion";
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            usuario: components["schemas"]["UsuarioToken"];
        };
        /** UsuarioToken */
        UsuarioToken: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre Completo */
            nombre_completo: string;
            /** Roles */
            roles: string[];
            /** Permisos */
            permisos: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_excel_api_v1_etl_upload_excel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_excel_api_v1_etl_upload_excel_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtlResult"];
                };
            };
            /** @description El archivo no cumple validaciones estructurales o de datos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtlValidationError"];
                };
            };
        };
    };
    predecir_demanda_api_v1_predictions_demand_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_carga_vigente_api_v1_routes_load_plans_get: {
        parameters: {
            query: {
                ruta_id: string;
                fecha_operacion: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gestionar_carga_api_v1_routes_load_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_existencias_api_v1_inventory_get: {
        parameters: {
            query?: {
                producto_id?: string | null;
                bajo_minimo?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_kardex_api_v1_inventory_kardex_get: {
        parameters: {
            query?: {
                producto_id?: string | null;
                tipo_movimiento?: components["schemas"]["TipoMovimiento"] | null;
                desde?: string | null;
                hasta?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KardexPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consultar_metricas_api_v1_ml_metrics_get: {
        parameters: {
            query: {
                desde: string;
                hasta: string;
                modelo_id?: string | null;
                tipo_evaluacion?: components["schemas"]["TipoEvaluacion"];
                producto_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reentrenar_api_v1_ml_models_retrain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_modelos_api_v1_ml_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelList"];
                };
            };
        };
    };
    estado_job_api_v1_ml_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_config_api_v1_ml_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlConfig"];
                };
            };
        };
    };
    guardar_config_api_v1_ml_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MlConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MlConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_alertas_api_v1_alerts_get: {
        parameters: {
            query?: {
                estado?: components["schemas"]["EstadoAlerta"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_rutas_api_v1_catalog_routes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteItem"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
