"""Esquema inicial (sección 3 de docs/architecture/00-especificacion.md).

Crea 24 tablas:
- Auth/RBAC: usuarios, roles, permisos, roles_permisos, usuarios_roles.
- Catálogos y stock: categorias, proveedores, productos, rutas, inventario, kardex.
- Operación: cargas_ruta, detalle_cargas, pedidos_proveedor, detalle_pedidos.
- Histórico/ETL: etl_lotes, ventas_historicas, comisiones.
- ML: modelos_ml, metricas_evaluacion, pronosticos_demanda, alertas,
  parametros_sistema, jobs_ml.

Incluye las restricciones e índices obligatorios de la sección 3.3 (índices
parciales únicos de ADR-03 y carga vigente, CHECK de ADR-07 y de la regla
cantidad_sugerida = min(demanda, stock)).

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 18:31:52.822981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('categoria_padre_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('categoria_padre_id <> id', name=op.f('ck_categorias_no_autorreferencia')),
    sa.ForeignKeyConstraint(['categoria_padre_id'], ['categorias.id'], name=op.f('fk_categorias_categoria_padre_id_categorias'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorias')),
    sa.UniqueConstraint('nombre', name=op.f('uq_categorias_nombre'))
    )
    op.create_index(op.f('ix_categorias_categoria_padre_id'), 'categorias', ['categoria_padre_id'], unique=False)
    op.create_table('permisos',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permisos')),
    sa.UniqueConstraint('codigo', name=op.f('uq_permisos_codigo'))
    )
    op.create_table('proveedores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('lead_time_dias', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('lead_time_dias >= 0', name=op.f('ck_proveedores_lead_time_no_negativo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proveedores')),
    sa.UniqueConstraint('nit', name=op.f('uq_proveedores_nit'))
    )
    op.create_table('roles',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('nombre', name=op.f('uq_roles_nombre'))
    )
    op.create_table('productos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sku', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.Column('proveedor_id', sa.UUID(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=20), server_default=sa.text("'unidad'"), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('precio_venta >= 0 AND costo_unitario >= 0 AND stock_minimo >= 0', name=op.f('ck_productos_valores_no_negativos')),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name=op.f('fk_productos_categoria_id_categorias'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('fk_productos_proveedor_id_proveedores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_productos')),
    sa.UniqueConstraint('sku', name=op.f('uq_productos_sku'))
    )
    op.create_index(op.f('ix_productos_categoria_id'), 'productos', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_productos_proveedor_id'), 'productos', ['proveedor_id'], unique=False)
    op.create_table('roles_permisos',
    sa.Column('rol_id', sa.SmallInteger(), nullable=False),
    sa.Column('permiso_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], name=op.f('fk_roles_permisos_permiso_id_permisos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], name=op.f('fk_roles_permisos_rol_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id', name=op.f('pk_roles_permisos'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('proveedor_id', sa.UUID(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('fk_usuarios_proveedor_id_proveedores'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email'))
    )
    op.create_index(op.f('ix_usuarios_proveedor_id'), 'usuarios', ['proveedor_id'], unique=False)
    op.create_table('etl_lotes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('archivo_nombre', sa.String(length=255), nullable=False),
    sa.Column('checksum_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('estado', sa.String(length=12), server_default=sa.text("'recibido'"), nullable=False),
    sa.Column('filas_totales', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('filas_validas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('filas_rechazadas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('errores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('recibido', 'validado', 'rechazado', 'cargado')", name=op.f('ck_etl_lotes_estado_valido')),
    sa.CheckConstraint('filas_totales >= 0 AND filas_validas >= 0 AND filas_rechazadas >= 0 AND filas_validas + filas_rechazadas <= filas_totales', name=op.f('ck_etl_lotes_conteos_coherentes')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_etl_lotes_usuario_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etl_lotes')),
    sa.UniqueConstraint('checksum_sha256', name=op.f('uq_etl_lotes_checksum_sha256'))
    )
    op.create_index(op.f('ix_etl_lotes_usuario_id'), 'etl_lotes', ['usuario_id'], unique=False)
    op.create_table('inventario',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('stock_reservado', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stock_actual >= 0 AND stock_reservado <= stock_actual', name=op.f('ck_inventario_integridad_existencias')),
    sa.CheckConstraint('stock_reservado >= 0', name=op.f('ck_inventario_reservado_no_negativo')),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_inventario_producto_id_productos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventario')),
    sa.UniqueConstraint('producto_id', name=op.f('uq_inventario_producto_id'))
    )
    op.create_table('kardex',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=12), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_resultante', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('referencia_tipo', sa.String(length=15), nullable=True),
    sa.Column('referencia_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('fecha_movimiento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("referencia_tipo IS NULL OR referencia_tipo IN ('carga_ruta', 'pedido', 'ajuste', 'etl')", name=op.f('ck_kardex_referencia_tipo_valida')),
    sa.CheckConstraint("tipo_movimiento IN ('entrada', 'salida', 'ajuste', 'reserva', 'liberacion')", name=op.f('ck_kardex_tipo_movimiento_valido')),
    sa.CheckConstraint('saldo_resultante >= 0', name=op.f('ck_kardex_saldo_no_negativo')),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_kardex_producto_id_productos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_kardex_usuario_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kardex'))
    )
    op.create_index('ix_kardex_producto_fecha', 'kardex', ['producto_id', sa.literal_column('fecha_movimiento DESC')], unique=False)
    op.create_index(op.f('ix_kardex_usuario_id'), 'kardex', ['usuario_id'], unique=False)
    op.create_table('modelos_ml',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('algoritmo', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=15), server_default=sa.text("'candidato'"), nullable=False),
    sa.Column('ruta_artefacto', sa.String(length=255), nullable=False),
    sa.Column('hash_artefacto', sa.CHAR(length=64), nullable=False),
    sa.Column('hiperparametros', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('esquema_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ventana_desde', sa.Date(), nullable=False),
    sa.Column('ventana_hasta', sa.Date(), nullable=False),
    sa.Column('motivo_entrenamiento', sa.String(length=15), nullable=False),
    sa.Column('entrenado_por', sa.UUID(), nullable=True),
    sa.Column('entrenado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('promovido_en', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("algoritmo IN ('sklearn', 'xgboost', 'lstm')", name=op.f('ck_modelos_ml_algoritmo_valido')),
    sa.CheckConstraint("estado <> 'produccion' OR promovido_en IS NOT NULL", name=op.f('ck_modelos_ml_produccion_promovido')),
    sa.CheckConstraint("estado IN ('candidato', 'produccion', 'archivado', 'descartado')", name=op.f('ck_modelos_ml_estado_valido')),
    sa.CheckConstraint("motivo_entrenamiento IN ('programado', 'manual', 'degradacion')", name=op.f('ck_modelos_ml_motivo_valido')),
    sa.CheckConstraint('ventana_desde < ventana_hasta', name=op.f('ck_modelos_ml_ventana_coherente')),
    sa.ForeignKeyConstraint(['entrenado_por'], ['usuarios.id'], name=op.f('fk_modelos_ml_entrenado_por_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modelos_ml')),
    sa.UniqueConstraint('nombre', 'version', name=op.f('uq_modelos_ml_nombre_version'))
    )
    op.create_index('uq_modelos_ml_produccion_nombre', 'modelos_ml', ['nombre'], unique=True, postgresql_where=sa.text("estado = 'produccion'"))
    op.create_table('parametros_sistema',
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actualizado_por', sa.UUID(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuarios.id'], name=op.f('fk_parametros_sistema_actualizado_por_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('clave', name=op.f('pk_parametros_sistema'))
    )
    op.create_table('pedidos_proveedor',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('proveedor_id', sa.UUID(), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=12), server_default=sa.text("'borrador'"), nullable=False),
    sa.Column('fecha_pedido', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('fecha_esperada', sa.Date(), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('borrador', 'enviado', 'confirmado', 'recibido', 'cancelado')", name=op.f('ck_pedidos_proveedor_estado_valido')),
    sa.CheckConstraint('fecha_esperada IS NULL OR fecha_esperada >= fecha_pedido', name=op.f('ck_pedidos_proveedor_fechas_coherentes')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_pedidos_proveedor_total_no_negativo')),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], name=op.f('fk_pedidos_proveedor_creado_por_usuarios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('fk_pedidos_proveedor_proveedor_id_proveedores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pedidos_proveedor'))
    )
    op.create_index(op.f('ix_pedidos_proveedor_creado_por'), 'pedidos_proveedor', ['creado_por'], unique=False)
    op.create_index('ix_pedidos_proveedor_proveedor_estado', 'pedidos_proveedor', ['proveedor_id', 'estado'], unique=False)
    op.create_table('rutas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('zona', sa.String(length=100), nullable=True),
    sa.Column('vendedor_id', sa.UUID(), nullable=True),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id'], name=op.f('fk_rutas_vendedor_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rutas')),
    sa.UniqueConstraint('codigo', name=op.f('uq_rutas_codigo'))
    )
    op.create_index(op.f('ix_rutas_vendedor_id'), 'rutas', ['vendedor_id'], unique=False)
    op.create_table('usuarios_roles',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('rol_id', sa.SmallInteger(), nullable=False),
    sa.Column('asignado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], name=op.f('fk_usuarios_roles_rol_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_usuarios_roles_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id', name=op.f('pk_usuarios_roles'))
    )
    op.create_table('alertas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tipo', sa.String(length=25), nullable=False),
    sa.Column('severidad', sa.String(length=12), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=True),
    sa.Column('modelo_id', sa.UUID(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=12), server_default=sa.text("'abierta'"), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resuelta_en', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado <> 'resuelta' OR resuelta_en IS NOT NULL", name=op.f('ck_alertas_resolucion_fechada')),
    sa.CheckConstraint("estado IN ('abierta', 'reconocida', 'resuelta')", name=op.f('ck_alertas_estado_valido')),
    sa.CheckConstraint("severidad IN ('info', 'advertencia', 'critica')", name=op.f('ck_alertas_severidad_valida')),
    sa.CheckConstraint("tipo IN ('stock_bajo', 'quiebre_proyectado', 'mape_umbral', 'etl_error')", name=op.f('ck_alertas_tipo_valido')),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_ml.id'], name=op.f('fk_alertas_modelo_id_modelos_ml'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_alertas_producto_id_productos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alertas'))
    )
    op.create_index('ix_alertas_estado_severidad_creada', 'alertas', ['estado', 'severidad', sa.literal_column('creada_en DESC')], unique=False)
    op.create_index(op.f('ix_alertas_modelo_id'), 'alertas', ['modelo_id'], unique=False)
    op.create_index(op.f('ix_alertas_producto_id'), 'alertas', ['producto_id'], unique=False)
    op.create_table('cargas_ruta',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ruta_id', sa.UUID(), nullable=False),
    sa.Column('fecha_operacion', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=25), server_default=sa.text("'borrador'"), nullable=False),
    sa.Column('modelo_id', sa.UUID(), nullable=False),
    sa.Column('generado_por', sa.UUID(), nullable=False),
    sa.Column('aprobado_por', sa.UUID(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('generada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aprobada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('borrador', 'pendiente_aprobacion', 'aprobada', 'rechazada', 'despachada')", name=op.f('ck_cargas_ruta_estado_valido')),
    sa.CheckConstraint("estado NOT IN ('aprobada', 'despachada') OR (aprobado_por IS NOT NULL AND aprobada_en IS NOT NULL)", name=op.f('ck_cargas_ruta_aprobacion_completa')),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuarios.id'], name=op.f('fk_cargas_ruta_aprobado_por_usuarios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generado_por'], ['usuarios.id'], name=op.f('fk_cargas_ruta_generado_por_usuarios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_ml.id'], name=op.f('fk_cargas_ruta_modelo_id_modelos_ml'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], name=op.f('fk_cargas_ruta_ruta_id_rutas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cargas_ruta'))
    )
    op.create_index(op.f('ix_cargas_ruta_generado_por'), 'cargas_ruta', ['generado_por'], unique=False)
    op.create_index(op.f('ix_cargas_ruta_modelo_id'), 'cargas_ruta', ['modelo_id'], unique=False)
    op.create_index('uq_cargas_ruta_vigente_ruta_fecha', 'cargas_ruta', ['ruta_id', 'fecha_operacion'], unique=True, postgresql_where=sa.text("estado IN ('borrador', 'pendiente_aprobacion', 'aprobada')"))
    op.create_table('jobs_ml',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tipo', sa.String(length=25), nullable=False),
    sa.Column('estado', sa.String(length=15), server_default=sa.text("'en_cola'"), nullable=False),
    sa.Column('parametros', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('solicitado_por', sa.UUID(), nullable=True),
    sa.Column('resultado_modelo_id', sa.UUID(), nullable=True),
    sa.Column('solicitado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('iniciado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("estado IN ('en_cola', 'en_ejecucion', 'completado', 'fallido')", name=op.f('ck_jobs_ml_estado_valido')),
    sa.CheckConstraint("tipo IN ('reentrenamiento', 'evaluacion_produccion', 'pronostico_nocturno')", name=op.f('ck_jobs_ml_tipo_valido')),
    sa.CheckConstraint('finalizado_en IS NULL OR iniciado_en IS NULL OR finalizado_en >= iniciado_en', name=op.f('ck_jobs_ml_tiempos_coherentes')),
    sa.ForeignKeyConstraint(['resultado_modelo_id'], ['modelos_ml.id'], name=op.f('fk_jobs_ml_resultado_modelo_id_modelos_ml'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitado_por'], ['usuarios.id'], name=op.f('fk_jobs_ml_solicitado_por_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs_ml'))
    )
    op.create_index('ix_jobs_ml_estado_solicitado', 'jobs_ml', ['estado', 'solicitado_en'], unique=False)
    op.create_table('metricas_evaluacion',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('modelo_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=True),
    sa.Column('tipo_evaluacion', sa.String(length=12), nullable=False),
    sa.Column('mae', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('rmse', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('mape', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('n_muestras', sa.Integer(), nullable=False),
    sa.Column('periodo_desde', sa.Date(), nullable=False),
    sa.Column('periodo_hasta', sa.Date(), nullable=False),
    sa.Column('supera_umbral', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('evaluado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo_evaluacion IN ('holdout', 'backtest', 'produccion')", name=op.f('ck_metricas_evaluacion_tipo_valido')),
    sa.CheckConstraint('mae >= 0 AND rmse >= 0', name=op.f('ck_metricas_evaluacion_errores_no_negativos')),
    sa.CheckConstraint('mape IS NULL OR mape >= 0', name=op.f('ck_metricas_evaluacion_mape_no_negativo')),
    sa.CheckConstraint('n_muestras > 0', name=op.f('ck_metricas_evaluacion_n_muestras_positivo')),
    sa.CheckConstraint('periodo_desde <= periodo_hasta', name=op.f('ck_metricas_evaluacion_periodo_coherente')),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_ml.id'], name=op.f('fk_metricas_evaluacion_modelo_id_modelos_ml'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_metricas_evaluacion_producto_id_productos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metricas_evaluacion'))
    )
    op.create_index('ix_metricas_evaluacion_modelo_tipo_periodo', 'metricas_evaluacion', ['modelo_id', 'tipo_evaluacion', sa.literal_column('periodo_hasta DESC')], unique=False)
    op.create_index(op.f('ix_metricas_evaluacion_producto_id'), 'metricas_evaluacion', ['producto_id'], unique=False)
    op.create_table('pronosticos_demanda',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('modelo_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('ruta_id', sa.UUID(), nullable=True),
    sa.Column('fecha_objetivo', sa.Date(), nullable=False),
    sa.Column('horizonte_dias', sa.Integer(), nullable=False),
    sa.Column('demanda_predicha', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('limite_inferior', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('limite_superior', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('demanda_real', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('generado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(limite_inferior IS NULL OR limite_inferior <= demanda_predicha) AND (limite_superior IS NULL OR demanda_predicha <= limite_superior)', name=op.f('ck_pronosticos_demanda_intervalo_coherente')),
    sa.CheckConstraint('demanda_predicha >= 0', name=op.f('ck_pronosticos_demanda_predicha_no_negativa')),
    sa.CheckConstraint('demanda_real IS NULL OR demanda_real >= 0', name=op.f('ck_pronosticos_demanda_real_no_negativa')),
    sa.CheckConstraint('horizonte_dias BETWEEN 1 AND 30', name=op.f('ck_pronosticos_demanda_horizonte_rango')),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_ml.id'], name=op.f('fk_pronosticos_demanda_modelo_id_modelos_ml'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_pronosticos_demanda_producto_id_productos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], name=op.f('fk_pronosticos_demanda_ruta_id_rutas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pronosticos_demanda')),
    sa.UniqueConstraint('modelo_id', 'producto_id', 'ruta_id', 'fecha_objetivo', 'horizonte_dias', name='uq_pronosticos_demanda_clave', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_pronosticos_demanda_fecha_producto', 'pronosticos_demanda', ['fecha_objetivo', 'producto_id'], unique=False)
    op.create_index(op.f('ix_pronosticos_demanda_ruta_id'), 'pronosticos_demanda', ['ruta_id'], unique=False)
    op.create_table('ventas_historicas',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('lote_id', sa.UUID(), nullable=False),
    sa.Column('fecha_venta', sa.Date(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('ruta_id', sa.UUID(), nullable=False),
    sa.Column('vendedor_id', sa.UUID(), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('cantidad >= 0 AND precio_unitario >= 0', name=op.f('ck_ventas_historicas_calidad_datos')),
    sa.CheckConstraint('monto_total >= 0', name=op.f('ck_ventas_historicas_monto_no_negativo')),
    sa.ForeignKeyConstraint(['lote_id'], ['etl_lotes.id'], name=op.f('fk_ventas_historicas_lote_id_etl_lotes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_ventas_historicas_producto_id_productos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], name=op.f('fk_ventas_historicas_ruta_id_rutas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id'], name=op.f('fk_ventas_historicas_vendedor_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ventas_historicas')),
    sa.UniqueConstraint('fecha_venta', 'producto_id', 'ruta_id', 'vendedor_id', name='uq_ventas_historicas_fecha_producto_ruta_vendedor', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_ventas_historicas_lote_id'), 'ventas_historicas', ['lote_id'], unique=False)
    op.create_index('ix_ventas_historicas_producto_fecha', 'ventas_historicas', ['producto_id', 'fecha_venta'], unique=False)
    op.create_index('ix_ventas_historicas_ruta_fecha', 'ventas_historicas', ['ruta_id', 'fecha_venta'], unique=False)
    op.create_index(op.f('ix_ventas_historicas_vendedor_id'), 'ventas_historicas', ['vendedor_id'], unique=False)
    op.create_table('comisiones',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vendedor_id', sa.UUID(), nullable=False),
    sa.Column('venta_id', sa.BigInteger(), nullable=False),
    sa.Column('periodo', sa.CHAR(length=7), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint("periodo ~ '^\\d{4}-(0[1-9]|1[0-2])$'", name=op.f('ck_comisiones_periodo_formato')),
    sa.CheckConstraint('monto >= 0', name=op.f('ck_comisiones_monto_no_negativo')),
    sa.CheckConstraint('porcentaje >= 0 AND porcentaje <= 100', name=op.f('ck_comisiones_porcentaje_rango')),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id'], name=op.f('fk_comisiones_vendedor_id_usuarios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas_historicas.id'], name=op.f('fk_comisiones_venta_id_ventas_historicas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comisiones')),
    sa.UniqueConstraint('venta_id', 'vendedor_id', name=op.f('uq_comisiones_venta_id_vendedor_id'))
    )
    op.create_index('ix_comisiones_vendedor_periodo', 'comisiones', ['vendedor_id', 'periodo'], unique=False)
    op.create_table('detalle_cargas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('carga_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('cantidad_predicha', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_disponible_al_generar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cantidad_sugerida', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cantidad_aprobada', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ajustado_por_stock', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('cantidad_aprobada IS NULL OR (cantidad_aprobada >= 0 AND cantidad_aprobada <= stock_disponible_al_generar)', name=op.f('ck_detalle_cargas_aprobada_no_excede_stock')),
    sa.CheckConstraint('cantidad_predicha >= 0 AND stock_disponible_al_generar >= 0 AND cantidad_sugerida >= 0', name=op.f('ck_detalle_cargas_cantidades_no_negativas')),
    sa.CheckConstraint('cantidad_sugerida = LEAST(cantidad_predicha, stock_disponible_al_generar)', name=op.f('ck_detalle_cargas_sugerida_min_demanda_stock')),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas_ruta.id'], name=op.f('fk_detalle_cargas_carga_id_cargas_ruta'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_detalle_cargas_producto_id_productos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detalle_cargas')),
    sa.UniqueConstraint('carga_id', 'producto_id', name=op.f('uq_detalle_cargas_carga_id_producto_id'))
    )
    op.create_index(op.f('ix_detalle_cargas_producto_id'), 'detalle_cargas', ['producto_id'], unique=False)
    op.create_table('detalle_pedidos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('alerta_origen_id', sa.UUID(), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('cantidad > 0 AND costo_unitario >= 0', name=op.f('ck_detalle_pedidos_valores_validos')),
    sa.ForeignKeyConstraint(['alerta_origen_id'], ['alertas.id'], name=op.f('fk_detalle_pedidos_alerta_origen_id_alertas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_proveedor.id'], name=op.f('fk_detalle_pedidos_pedido_id_pedidos_proveedor'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_detalle_pedidos_producto_id_productos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detalle_pedidos')),
    sa.UniqueConstraint('pedido_id', 'producto_id', name=op.f('uq_detalle_pedidos_pedido_id_producto_id'))
    )
    op.create_index(op.f('ix_detalle_pedidos_alerta_origen_id'), 'detalle_pedidos', ['alerta_origen_id'], unique=False)
    op.create_index(op.f('ix_detalle_pedidos_producto_id'), 'detalle_pedidos', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_pedidos_producto_id'), table_name='detalle_pedidos')
    op.drop_index(op.f('ix_detalle_pedidos_alerta_origen_id'), table_name='detalle_pedidos')
    op.drop_table('detalle_pedidos')
    op.drop_index(op.f('ix_detalle_cargas_producto_id'), table_name='detalle_cargas')
    op.drop_table('detalle_cargas')
    op.drop_index('ix_comisiones_vendedor_periodo', table_name='comisiones')
    op.drop_table('comisiones')
    op.drop_index(op.f('ix_ventas_historicas_vendedor_id'), table_name='ventas_historicas')
    op.drop_index('ix_ventas_historicas_ruta_fecha', table_name='ventas_historicas')
    op.drop_index('ix_ventas_historicas_producto_fecha', table_name='ventas_historicas')
    op.drop_index(op.f('ix_ventas_historicas_lote_id'), table_name='ventas_historicas')
    op.drop_table('ventas_historicas')
    op.drop_index(op.f('ix_pronosticos_demanda_ruta_id'), table_name='pronosticos_demanda')
    op.drop_index('ix_pronosticos_demanda_fecha_producto', table_name='pronosticos_demanda')
    op.drop_table('pronosticos_demanda')
    op.drop_index(op.f('ix_metricas_evaluacion_producto_id'), table_name='metricas_evaluacion')
    op.drop_index('ix_metricas_evaluacion_modelo_tipo_periodo', table_name='metricas_evaluacion')
    op.drop_table('metricas_evaluacion')
    op.drop_index('ix_jobs_ml_estado_solicitado', table_name='jobs_ml')
    op.drop_table('jobs_ml')
    op.drop_index('uq_cargas_ruta_vigente_ruta_fecha', table_name='cargas_ruta', postgresql_where=sa.text("estado IN ('borrador', 'pendiente_aprobacion', 'aprobada')"))
    op.drop_index(op.f('ix_cargas_ruta_modelo_id'), table_name='cargas_ruta')
    op.drop_index(op.f('ix_cargas_ruta_generado_por'), table_name='cargas_ruta')
    op.drop_table('cargas_ruta')
    op.drop_index(op.f('ix_alertas_producto_id'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_modelo_id'), table_name='alertas')
    op.drop_index('ix_alertas_estado_severidad_creada', table_name='alertas')
    op.drop_table('alertas')
    op.drop_table('usuarios_roles')
    op.drop_index(op.f('ix_rutas_vendedor_id'), table_name='rutas')
    op.drop_table('rutas')
    op.drop_index('ix_pedidos_proveedor_proveedor_estado', table_name='pedidos_proveedor')
    op.drop_index(op.f('ix_pedidos_proveedor_creado_por'), table_name='pedidos_proveedor')
    op.drop_table('pedidos_proveedor')
    op.drop_table('parametros_sistema')
    op.drop_index('uq_modelos_ml_produccion_nombre', table_name='modelos_ml', postgresql_where=sa.text("estado = 'produccion'"))
    op.drop_table('modelos_ml')
    op.drop_index(op.f('ix_kardex_usuario_id'), table_name='kardex')
    op.drop_index('ix_kardex_producto_fecha', table_name='kardex')
    op.drop_table('kardex')
    op.drop_table('inventario')
    op.drop_index(op.f('ix_etl_lotes_usuario_id'), table_name='etl_lotes')
    op.drop_table('etl_lotes')
    op.drop_index(op.f('ix_usuarios_proveedor_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('roles_permisos')
    op.drop_index(op.f('ix_productos_proveedor_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_categoria_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_table('roles')
    op.drop_table('proveedores')
    op.drop_table('permisos')
    op.drop_index(op.f('ix_categorias_categoria_padre_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
