"""Liquidación diaria de ventas (ADR-14).

- `liquidaciones_diarias` y `liquidacion_detalles` (unidades + dinero por ruta/vendedor/día).
- `etl_lotes.origen` (`excel_historico` | `liquidacion`): los lotes existentes quedan como Excel.
- `alertas.tipo` admite `diferencia_caja` (autogenerate no compara CHECK: ajustado a mano).
- `pronosticos_demanda.demanda_censurada` y `modelos_ml.fuentes_datos` (trazabilidad ML).

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 19:34:18.319754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liquidaciones_diarias',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('ruta_id', sa.UUID(), nullable=False),
    sa.Column('vendedor_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=10), server_default=sa.text("'borrador'"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('lote_id', sa.UUID(), nullable=True),
    sa.Column('venta_total', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_efectivo', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_transferencia', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_credito', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('cobro_saldos_anteriores', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('gastos_ruta', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('efectivo_esperado', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('efectivo_entregado', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('diferencia_caja', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cerrado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anulado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anulado_motivo', sa.Text(), nullable=True),
    sa.Column('historial', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.CheckConstraint("estado <> 'anulada' OR (anulado_en IS NOT NULL AND anulado_motivo IS NOT NULL)", name=op.f('ck_liquidaciones_diarias_anulacion_completa')),
    sa.CheckConstraint("estado <> 'cerrada' OR (cerrado_en IS NOT NULL AND lote_id IS NOT NULL)", name=op.f('ck_liquidaciones_diarias_cierre_completo')),
    sa.CheckConstraint("estado <> 'cerrada' OR venta_total = total_efectivo + total_transferencia + total_credito", name=op.f('ck_liquidaciones_diarias_venta_igual_pagos')),
    sa.CheckConstraint("estado IN ('borrador', 'cerrada', 'anulada')", name=op.f('ck_liquidaciones_diarias_estado_valido')),
    sa.CheckConstraint('efectivo_esperado = total_efectivo + cobro_saldos_anteriores - gastos_ruta AND diferencia_caja = efectivo_entregado - efectivo_esperado', name=op.f('ck_liquidaciones_diarias_cuadre_caja_coherente')),
    sa.CheckConstraint('venta_total >= 0 AND total_efectivo >= 0 AND total_transferencia >= 0 AND total_credito >= 0 AND cobro_saldos_anteriores >= 0 AND gastos_ruta >= 0 AND efectivo_entregado >= 0', name=op.f('ck_liquidaciones_diarias_montos_no_negativos')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_liquidaciones_diarias_version_positiva')),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], name=op.f('fk_liquidaciones_diarias_creado_por_usuarios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lote_id'], ['etl_lotes.id'], name=op.f('fk_liquidaciones_diarias_lote_id_etl_lotes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], name=op.f('fk_liquidaciones_diarias_ruta_id_rutas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id'], name=op.f('fk_liquidaciones_diarias_vendedor_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_liquidaciones_diarias'))
    )
    op.create_index(op.f('ix_liquidaciones_diarias_creado_por'), 'liquidaciones_diarias', ['creado_por'], unique=False)
    op.create_index('ix_liquidaciones_diarias_fecha_ruta', 'liquidaciones_diarias', ['fecha', 'ruta_id'], unique=False)
    op.create_index(op.f('ix_liquidaciones_diarias_lote_id'), 'liquidaciones_diarias', ['lote_id'], unique=False)
    op.create_index(op.f('ix_liquidaciones_diarias_vendedor_id'), 'liquidaciones_diarias', ['vendedor_id'], unique=False)
    op.create_index('uq_liquidaciones_diarias_vigente', 'liquidaciones_diarias', ['fecha', 'ruta_id', 'vendedor_id'], unique=True, postgresql_where=sa.text("estado <> 'anulada'"))
    op.create_table('liquidacion_detalles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('liquidacion_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('cantidad_cargada', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cantidad_vendida', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cantidad_devuelta', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('cantidad_merma', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('agotado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('justificacion_carga', sa.Text(), nullable=True),
    sa.CheckConstraint('cantidad_cargada >= 0 AND cantidad_vendida >= 0 AND cantidad_devuelta >= 0 AND cantidad_merma >= 0 AND precio_unitario >= 0 AND monto_total >= 0', name=op.f('ck_liquidacion_detalles_valores_no_negativos')),
    sa.CheckConstraint('cantidad_vendida + cantidad_devuelta + cantidad_merma <= cantidad_cargada', name=op.f('ck_liquidacion_detalles_unidades_no_exceden_cargada')),
    sa.CheckConstraint('monto_total = round(cantidad_vendida * precio_unitario, 2)', name=op.f('ck_liquidacion_detalles_monto_coherente')),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones_diarias.id'], name=op.f('fk_liquidacion_detalles_liquidacion_id_liquidaciones_diarias'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_liquidacion_detalles_producto_id_productos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_liquidacion_detalles')),
    sa.UniqueConstraint('liquidacion_id', 'producto_id', name=op.f('uq_liquidacion_detalles_liquidacion_id_producto_id'))
    )
    op.create_index(op.f('ix_liquidacion_detalles_producto_id'), 'liquidacion_detalles', ['producto_id'], unique=False)
    op.add_column('etl_lotes', sa.Column('origen', sa.String(length=20), server_default=sa.text("'excel_historico'"), nullable=False))
    op.add_column('modelos_ml', sa.Column('fuentes_datos', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('pronosticos_demanda', sa.Column('demanda_censurada', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint(
        'origen_valido', 'etl_lotes', "origen IN ('excel_historico', 'liquidacion')"
    )
    op.drop_constraint(op.f('ck_alertas_tipo_valido'), 'alertas', type_='check')
    op.create_check_constraint(
        'tipo_valido',
        'alertas',
        "tipo IN ('stock_bajo', 'quiebre_proyectado', 'mape_umbral', 'etl_error', 'diferencia_caja')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # La alerta `diferencia_caja` no existe en el esquema anterior.
    op.execute("DELETE FROM alertas WHERE tipo = 'diferencia_caja'")
    op.drop_constraint(op.f('ck_alertas_tipo_valido'), 'alertas', type_='check')
    op.create_check_constraint(
        'tipo_valido',
        'alertas',
        "tipo IN ('stock_bajo', 'quiebre_proyectado', 'mape_umbral', 'etl_error')",
    )
    op.drop_constraint(op.f('ck_etl_lotes_origen_valido'), 'etl_lotes', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pronosticos_demanda', 'demanda_censurada')
    op.drop_column('modelos_ml', 'fuentes_datos')
    op.drop_column('etl_lotes', 'origen')
    op.drop_index(op.f('ix_liquidacion_detalles_producto_id'), table_name='liquidacion_detalles')
    op.drop_table('liquidacion_detalles')
    op.drop_index('uq_liquidaciones_diarias_vigente', table_name='liquidaciones_diarias', postgresql_where=sa.text("estado <> 'anulada'"))
    op.drop_index(op.f('ix_liquidaciones_diarias_vendedor_id'), table_name='liquidaciones_diarias')
    op.drop_index(op.f('ix_liquidaciones_diarias_lote_id'), table_name='liquidaciones_diarias')
    op.drop_index('ix_liquidaciones_diarias_fecha_ruta', table_name='liquidaciones_diarias')
    op.drop_index(op.f('ix_liquidaciones_diarias_creado_por'), table_name='liquidaciones_diarias')
    op.drop_table('liquidaciones_diarias')
    # ### end Alembic commands ###
